// `milton init` — bootstrap a new Milton-shaped agent on disk.
//
// PR-2 lands the directory + file generation. Flair pair (Ed25519 key
// + Agent record) is PR-3; mail consumer is PR-4; Discord+cron are PR-5+.
//
// Layout written:
//   ~/agents/<name>/
//     ├── milton.yaml         # canonical config
//     ├── soul.md             # role's seed soul (caller-editable)
//     ├── bin/<name>          # generated launcher
//     ├── work/               # working dir (empty)
//     ├── memory/             # local memory cache (empty)
//     └── .pi-agent/          # pi-coding-agent state (empty; populated on first run)

import { mkdirSync, writeFileSync, chmodSync, existsSync } from "node:fs";
import { join } from "node:path";
import { homedir } from "node:os";
import type { MiltonRole } from "./index.js";
import { loadRole } from "./role-loader.js";

// Same character class loadRole uses — agent names are filesystem paths,
// keep them strict-safe.
const AGENT_NAME = /^[a-z0-9-]+$/;

export interface InitOptions {
  name: string;
  role: MiltonRole;
  provider: string;
  model: string;
  // Where the agent lives. Defaults to ~/agents/<name>/. Tests override.
  agentsRoot?: string;
  // Used for the launcher's PATH hint. Defaults to the Bun runtime we expect.
  bunPath?: string;
  // If true, refuse to overwrite an existing agent dir. Defaults to true.
  noClobber?: boolean;
}

export interface InitResult {
  agentDir: string;
  files: string[];
}

export function initAgent(opts: InitOptions): InitResult {
  if (!AGENT_NAME.test(opts.name)) {
    throw new Error(`invalid agent name: ${opts.name} (must match ${AGENT_NAME})`);
  }
  // Validates the role + loads the template. Throws on unknown / unsafe role.
  const template = loadRole(opts.role);
  const root = opts.agentsRoot ?? join(homedir(), "agents");
  const agentDir = join(root, opts.name);
  const noClobber = opts.noClobber !== false;

  if (existsSync(agentDir) && noClobber) {
    throw new Error(`agent dir already exists: ${agentDir} (pass --force to overwrite)`);
  }

  const written: string[] = [];

  // Top-level + subdirs
  mkdirSync(join(agentDir, "bin"), { recursive: true });
  mkdirSync(join(agentDir, "work"), { recursive: true });
  mkdirSync(join(agentDir, "memory"), { recursive: true });
  mkdirSync(join(agentDir, ".pi-agent"), { recursive: true });

  // soul.md (from role template; user editable)
  const soulPath = join(agentDir, "soul.md");
  writeFileSync(soulPath, template.soul);
  written.push(soulPath);

  // milton.yaml — canonical config
  const yamlPath = join(agentDir, "milton.yaml");
  writeFileSync(yamlPath, renderMiltonYaml(opts, template.tools.allow));
  written.push(yamlPath);

  // bin/<name> launcher
  const binPath = join(agentDir, "bin", opts.name);
  writeFileSync(binPath, renderLauncher(opts));
  chmodSync(binPath, 0o755);
  written.push(binPath);

  return { agentDir, files: written };
}

function renderMiltonYaml(opts: InitOptions, toolsAllow: string[]): string {
  // Hand-rolled to avoid pulling in a yaml dependency for the surface PR.
  // PR-3 (Flair pair) will swap in a real yaml emitter.
  const tools = toolsAllow.map((t) => `    - ${t}`).join("\n");
  return `# Milton config — generated by 'milton init'. Edit freely.
agent:
  id: ${opts.name}
  name: ${capitalize(opts.name)}
  role: ${opts.role}

provider:
  name: ${opts.provider}
  model: ${opts.model}

identity:
  # PR-3 populates these (Ed25519 keypair + Flair Agent record).
  flair_url: http://127.0.0.1:9926
  key_file: ~/.flair/keys/${opts.name}.key
  pub_file: ~/.flair/keys/${opts.name}.pub

channels:
  tps_mail:
    inbox: ~/.tps/mail/${opts.name}

# Add cron entries here:
# cron:
#   - name: morning_briefing
#     schedule: "0 9 * * *"
#     prompt: "Compose Nathan's morning briefing."

tools:
  allow:
${tools}
`;
}

function renderLauncher(opts: InitOptions): string {
  // sh shebang (NOT zsh) — re-sourcing ~/.zshenv on every invocation
  // clobbers env-prefix calls like FOO=bar <agent>. See
  // feedback_shebang_env_prefix in flint's memory.
  return `#!/bin/sh
# Generated by 'milton init'. Don't edit — re-run init to update.
# Edit ~/agents/${opts.name}/milton.yaml for config changes.

AGENT_DIR=${homedirEscape()}/agents/${opts.name}
export PI_CODING_AGENT_DIR="$AGENT_DIR/.pi-agent"

# Identity for any git commits the agent makes
export GIT_AUTHOR_NAME="${capitalize(opts.name)}"
export GIT_AUTHOR_EMAIL="${opts.name}@tps.dev"
export GIT_COMMITTER_NAME="${capitalize(opts.name)}"
export GIT_COMMITTER_EMAIL="${opts.name}@tps.dev"

cd "$AGENT_DIR/work"
exec pi --provider ${opts.provider} --model ${opts.model} "$@"
`;
}

function capitalize(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}

function homedirEscape(): string {
  // Launcher script reads $HOME at runtime, not at generation time —
  // makes the launcher portable across users / hostnames.
  return "$HOME";
}
