// launchd service install + lifecycle (`bob up` / `down` / `restart`).
//
// The agent owns its runtime (spec §3): each agent runs as its OWN launchd
// user-agent unit that hosts the persistent process (`bob serve <agent>` →
// runPersistent). Bob installs the unit; Bob does NOT babysit the process —
// launchd's KeepAlive restarts it on crash, RunAtLoad starts it on login.
//
// SECURITY (Sherlock): the generated plist NEVER embeds the bot token (or any
// secret). The discord capability reads its token from a FILE PATH carried in
// the agent's bob.yaml `discord.tokenFile` block (see @tpsdev-ai/bob-cap-discord
// config.ts) — the persistent process reads it from disk at startup and holds
// it only in memory. The plist only references the agent NAME + the bob binary.
// No env-var secrets, no inline token, nothing logged.
//
// TESTABILITY: every OS interaction is injected. `writeFile` writes the plist;
// `runLaunchctl` shells out to launchctl. Tests pass capturing fakes so we
// never touch the real LaunchAgents dir or launchctl.

import { spawnSync } from "node:child_process";
import { mkdirSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { dirname, join } from "node:path";

// Same strict class init.ts/run.ts use — agent names are filesystem paths AND
// get embedded in the plist Label / file name, so this doubles as path + XML
// injection defense (no `..`, no `/`, no `<`, no whitespace).
const AGENT_NAME = /^[a-z0-9-]+$/;

// launchd domain target for a user agent: gui/<uid>. Used by bootstrap/bootout/
// kickstart. We resolve <uid> at call time (injectable for tests).
function guiDomain(uid: number): string {
  return `gui/${uid}`;
}

// The launchd Label for an agent's unit. Stable + unique per agent.
export function serviceLabel(name: string): string {
  return `ai.tpsdev.bob.${name}`;
}

// The plist file path for an agent's unit (per-user LaunchAgents).
export function plistPath(name: string, home: string = homedir()): string {
  return join(home, "Library", "LaunchAgents", `${serviceLabel(name)}.plist`);
}

export interface RenderPlistOptions {
  name: string;
  // Absolute path to the `bob` binary the unit runs. launchd uses a minimal
  // PATH, so this MUST be absolute (the caller resolves it). Required.
  bobBin: string;
  // Optional model override passed through to `bob serve` (→ runPersistent).
  model?: string;
  // The agent's home dir for stdout/stderr log paths + WorkingDirectory.
  // Defaults to ~. The agent's working dir is <home>/agents/<name>/work.
  home?: string;
}

// Render the per-agent launchd plist. KeepAlive (restart on crash) + RunAtLoad
// (start on login). ProgramArguments run `bob serve <name>` — the persistent
// entrypoint. NO token, NO secret env vars — see the security note above.
export function renderPlist(opts: RenderPlistOptions): string {
  if (!AGENT_NAME.test(opts.name)) {
    throw new Error(`invalid agent name: ${JSON.stringify(opts.name)} (must match ${AGENT_NAME})`);
  }
  const home = opts.home ?? homedir();
  const label = serviceLabel(opts.name);
  const workDir = join(home, "agents", opts.name, "work");
  const logDir = join(home, "agents", opts.name);

  // ProgramArguments: the bob binary + the persistent subcommand. Each arg is
  // its own <string> — no shell, so no quoting/injection surface. The agent
  // name already passed the strict regex above; model (if any) is XML-escaped
  // defensively even though it comes from a trusted flag.
  const args = [opts.bobBin, "serve", opts.name];
  if (opts.model) args.push("--model", opts.model);
  const programArgs = args.map((a) => `    <string>${xmlEscape(a)}</string>`).join("\n");

  return `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<!-- Generated by 'bob install-service ${xmlEscape(opts.name)}'. Don't edit — re-run to update. -->
<!-- The agent runs itself: KeepAlive restarts on crash, RunAtLoad starts on login. -->
<!-- No credentials here by design: capabilities read theirs from file paths in bob.yaml. -->
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>${label}</string>
  <key>ProgramArguments</key>
  <array>
${programArgs}
  </array>
  <key>WorkingDirectory</key>
  <string>${xmlEscape(workDir)}</string>
  <key>RunAtLoad</key>
  <true/>
  <key>KeepAlive</key>
  <true/>
  <key>ProcessType</key>
  <string>Interactive</string>
  <key>StandardOutPath</key>
  <string>${xmlEscape(join(logDir, "service.out.log"))}</string>
  <key>StandardErrorPath</key>
  <string>${xmlEscape(join(logDir, "service.err.log"))}</string>
</dict>
</plist>
`;
}

// XML-escape a value for safe embedding in the plist. Defense in depth: the
// agent name already passed the strict regex, but bobBin / model / paths are
// escaped so a stray `&`/`<` can never break the XML.
function xmlEscape(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&apos;");
}

// --- Lifecycle (`bob up` / `down` / `restart`) ----------------------------

// Shells out to launchctl. Injected in tests so we never run real launchctl.
// Returns the exit code; non-zero throws in the wrappers below with the args
// (never any secret — there are none in these commands).
export type LaunchctlRunner = (args: string[]) => Promise<{ code: number; stderr: string }>;

export interface ServiceOpsDeps {
  // Write the plist to disk (install-service). Injected in tests.
  writeFile?: (path: string, contents: string) => void;
  // Run launchctl. Injected in tests.
  runLaunchctl?: LaunchctlRunner;
  // Resolve the current uid for the gui domain target. Injected in tests.
  getUid?: () => number;
  // Home dir override (tests).
  home?: string;
}

export interface InstallServiceOptions extends RenderPlistOptions, ServiceOpsDeps {}

// Write the agent's launchd plist to ~/Library/LaunchAgents. Does NOT load it
// (that's `bob up`) — install + start are separate so re-installing an updated
// unit while it's running is a `down` → `install` → `up` (or `restart`).
export function installService(opts: InstallServiceOptions): { plistPath: string } {
  const path = plistPath(opts.name, opts.home);
  const contents = renderPlist(opts);
  const write =
    opts.writeFile ??
    ((p: string, c: string) => {
      mkdirSync(dirname(p), { recursive: true });
      writeFileSync(p, c, "utf8");
    });
  write(path, contents);
  return { plistPath: path };
}

export interface LifecycleOptions extends ServiceOpsDeps {
  name: string;
}

const defaultRunLaunchctl: LaunchctlRunner = async (args: string[]) => {
  const r = spawnSync("launchctl", args, { encoding: "utf8" });
  return { code: r.status ?? 1, stderr: r.stderr ?? "" };
};

async function launchctl(deps: ServiceOpsDeps, args: string[]): Promise<void> {
  const runner = deps.runLaunchctl ?? defaultRunLaunchctl;
  const { code, stderr } = await runner(args);
  if (code !== 0) {
    throw new Error(
      `launchctl ${args.join(" ")} failed (exit ${code})${stderr ? `: ${stderr.trim()}` : ""}`,
    );
  }
}

function resolveUid(deps: ServiceOpsDeps): number {
  return (deps.getUid ?? (() => process.getuid?.() ?? 0))();
}

// `bob up <agent>` — load + start the unit. `bootstrap` registers it into the
// user's gui domain; RunAtLoad then starts it. Idempotent-ish: bootstrap on an
// already-loaded unit errors, so callers re-running should `down` first (or use
// `restart`).
export async function up(opts: LifecycleOptions): Promise<void> {
  const path = plistPath(opts.name, opts.home);
  const domain = guiDomain(resolveUid(opts));
  await launchctl(opts, ["bootstrap", domain, path]);
}

// `bob down <agent>` — stop + unload the unit. `bootout` removes it from the
// domain (KeepAlive won't restart a booted-out unit).
export async function down(opts: LifecycleOptions): Promise<void> {
  const path = plistPath(opts.name, opts.home);
  const domain = guiDomain(resolveUid(opts));
  await launchctl(opts, ["bootout", domain, path]);
}

// `bob restart <agent>` — GRACEFUL restart. `kickstart -k` sends SIGTERM to the
// running process (our persistent runtime disposes the session on SIGTERM —
// awaits in-flight, session.dispose()), then relaunches it. The session's
// durable on-disk state + Flair memory mean the agent comes back warm. This is
// also the "apply changes" step for the evolve loop (align / new capability →
// restart → agent back with new equipment).
export async function restart(opts: LifecycleOptions): Promise<void> {
  const domain = guiDomain(resolveUid(opts));
  const target = `${domain}/${serviceLabel(opts.name)}`;
  await launchctl(opts, ["kickstart", "-k", target]);
}
